version: '3.0'
maintainer: "operation@shiwaforce.com"

#before_script:
#    - ls -l

checkout:
    - . https://github.com/docker/example-voting-app.git

working-directory: example-voting-app

plan:
    default:    docker-compose.yml
    javaworker: docker-compose-javaworker.yml
    simple:     docker-compose-simple.yml
